# Generated by Django 3.0 on 2020-01-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_auto_20200130_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
